# Deployment config for Identity Server deployment
[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"
disable_addressing = true

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

[database.user]
url = "jdbc:mysql://wso2is-mysql-db-service:3306/WSO2IS_SHARED_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[database.user.pool_options]
validationQuery = "SELECT 1"

[database.identity_db]
type = "mysql"
url = "jdbc:mysql://wso2is-mysql-db-service:3306/WSO2IS_IDENTITY_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"
[database.identity_db.pool_options]
validationQuery="SELECT 1"

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://wso2is-mysql-db-service:3306/WSO2IS_SHARED_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"
[database.shared_db.pool_options]
validationQuery="SELECT 1"

[keystore.primary]
file_name = "wso2carbon.jks"
password = "wso2carbon"

[truststore]
file_name="client-truststore.jks"
password="wso2carbon"
type="JKS"

[account_recovery.endpoint.auth]
hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

[identity.auth_framework.endpoint]
app_password= "dashboard"

[database.bps_database]
url = "jdbc:mysql://wso2is-mysql-db-service:3306/WSO2IS_BPS_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[database.bps_database.pool_options]
validationQuery = "SELECT 1"

[[datasource]]
id = "WSO2ConsentDS"
url = "jdbc:mysql://wso2is-mysql-db-service:3306/WSO2IS_CONSENT_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"
"pool_options.validationQuery"="SELECT 1"
"pool_options.maxActive"=50
"pool_options.maxWait" = 60000 # wait in milliseconds
"pool_options.testOnBorrow" = true
"pool_options.jmxEnabled" = false
[authentication.consent]
data_source="jdbc/WSO2ConsentDS"

[carbon_health_check]
enable= true
[carbon_health_check.health_checker.data_source_health_checker.properties]
'monitored.datasources' = "jdbc/WSO2CarbonDB,jdbc/WSO2UM_DB,jdbc/SHARED_DB"

#SMTP email server configurations
[output_adapter.email]
from_address= "is.demo@wso2.com"
username= "admin"
password= "admin"
hostname= "mailserver"
port= 1025
enable_start_tls= true
enable_authentication= true

[recaptcha]
enabled = "true"
api_url = "https://www.google.com/recaptcha/api.js"
verify_url = "https://www.google.com/recaptcha/api/siteverify"
site_key="6LfoXQEVAAA"
secret_key="6LfoXQEVAAA"

#Enable access for sample
[identity_mgt.user_onboarding]
enable_email_verification = true

[[resource.access_control]]
context = "(.*)/sample-auth/(.*)"
secure = false
http_method = "all"

#Enable Email OTP config
[authentication.authenticator.email_otp]
name ="EmailOTP"
enable=true
[authentication.authenticator.email_otp.parameters]
EMAILOTPAuthenticationEndpointURL = "https://localhost:9443/emailotpauthenticationendpoint/emailotp.jsp"
EmailOTPAuthenticationEndpointErrorPage = "https://localhost:9443/emailotpauthenticationendpoint/emailotpError.jsp"
EmailAddressRequestPage = "https://localhost:9443/emailotpauthenticationendpoint/emailAddress.jsp"
usecase = "local"
secondaryUserstore = "primary"
EMAILOTPMandatory = false
sendOTPToFederatedEmailAttribute = false
federatedEmailAttributeKey = "email"
EmailOTPEnableByUserClaim = true
CaptureAndUpdateEmailAddress = true
showEmailAddressInUI = true
useEventHandlerBasedEmailSender = true
