name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Private Registry
        uses: docker/login-action@v1
        with:
          registry: docker.wso2.com
          username: ${{ secrets.WSO2_SUB_USER }}
          password: ${{ secrets.WSO2_SUB_PASS }}
      - name: Pull image
        run: docker pull docker.wso2.com/wso2is:5.11.0.0
      - name: Log level
        run: docker image inspect --format '{{ index .Config.Labels "update_level"}}' docker.wso2.com/wso2is:5.11.0.0
  
