name: Docker Compose CI

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Private Registry
        uses: docker/login-action@v1
        with:
          registry: docker.wso2.com
          username: ${{ secrets.WSO2_SUB_USER }}
          password: ${{ secrets.WSO2_SUB_PASS }}
      - uses: actions/checkout@v2
      - name: Build the stack
        run: ls -la demo-is
      - name: Build the stack
        run: pwd
        working-directory: ./demo-is/compose
